### ISSUE TITLE
Add functionality to list all available pictures (Torbjørn)

### ISSUE THREAD

**Issue by perrosvik** [perrosvik/DAT153-OBLIG1-THPMR#6]

**Comment by perrosvik** [comment]
Need to add database integration

**Comment by Houseboo** [comment]
Can't find a way to import a list with persons from the database. Show me how, and I can probably do the rest.

**Comment by perrosvik** [comment]
Add this class at the bottom of PictureGallery class:

 private class GetPersons extends AsyncTask<Void, Void, ArrayList<Person>> {
        @Override
        protected ArrayList<Person> doInBackground(Void... params) {
            db = Room.databaseBuilder(getApplicationContext(), AppDatabase.class, "database-name").build();
            return (ArrayList<Person>) db.appDao().loadAllPersons();
        }

       protected void onPostExecute(ArrayList<Person> temp) {
           if (temp != null){
               persons.addAll(temp);
               //Do stuff after you get the list from the database if necessary
              //You probably need to tell the adapter to update its content
           }
       }
    }

Then in onCreate for PictureGallery:
//This is to create Person objects from the built in names and pictures
String[] names = getResources().getStringArray(R.array.list_names);
persons = new ArrayList<>();
   
for(int i = 0; i < 4; i++) {
            persons.add(new Person(names[i], "android.resource://dat153.hvl.no.nameapp/drawable/cat" +i));
  }

Then you call: 
        new GetPersons().execute();
To get the list from the database

**Comment by perrosvik** [comment]
You don't need PersonAdapter in PictureGallery, since its an adapter specifically for displaying the names in the ListNamesActivity

**Comment by Houseboo** [comment]
"Then you call:
new GetPersons().execute();
To get the list from the database"

Can I save this list into a variable somehow? 

Example:
list = new ArrayList<>();
list = new GetPersons().execute();   //I know this won't work, but it just serves to show what I intend to do

**Comment by perrosvik** [comment]
protected void onPostExecute(ArrayList<Person> temp) {
       if (temp != null){
           **persons.addAll(temp);**
           //Do stuff after you get the list from the database if necessary
          //You probably need to tell the adapter to update its content
       }
   }

List from database is added to Persons in postExecute

**Comment by Houseboo** [comment]
Aaaah, I see! Thx (Y)
